<?php
/**
 *  @file
 *  Standard Drupal hook implementations in support of Dribbble module.
 */

/**
 *  Implements hook_menu().
 */
function dribbble_menu() {

  $items = array();

  $items['admin/config/content/dribbble'] = array(
    'file' => 'inc/dribbble.admin.inc',
    'title' => 'Dribbble',
    'description' => 'Configure Dribbble module settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dribbble_admin'),
    'access arguments' => array('administer dribbble'),
    'type' => MENU_NORMAL_ITEM
  );

  if (module_exists('dribbble_feed') || module_exists('shot_node')) {
    $items['admin/config/content/dribbble/settings'] = array(
      'title' => 'Dribbble Settings',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -10
    );
  }

  if (module_exists('shot_node')) {
    $items['admin/config/content/dribbble/shot-node'] = array(
      'file' => 'shot_node/inc/shot_node.admin.inc',
      'title' => t('Shot Node Settings'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('shot_node_admin'),
      'access arguments' => array('administer dribbble'),
      'type' => MENU_LOCAL_TASK
    );
  }

  return $items;

}

/**
 *  Implements hook_permission().
 */
function dribbble_permission() {

  return array(
    'administer dribbble' => array(
      'title' => t('Administer Dribbble settings'),
      'description' => t('@todo')
    ),
    'view dribbble' => array(
      'title' => t('View Dribbble content'),
      'description' => t('@todo')
    )
  );

}